name: desk

channels:
    - astropy

dependencies:
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx
    - sphinx-astropy
    - sphinx_automodapi
    - Pillow

  # - pip:
  #     - numpy
