name: desk

channels:
    - astropy

dependencies:
    - astropy
    - Cython
    - matplotlib
    - sphinx
    - sphinx-astropy
    - sphinx_automodapi
    - Pillow

- name: Codecov
  uses: codecov/codecov-action@v3.1.1
