name: desk

channels:
    - conda-forge

dependencies:
    - astropy
    - scipy
    - numpy
    - Cython
    - matplotlib
    - sphinx
    - sphinx-astropy
    - sphinx_automodapi
    - Pillow
    - pip
