# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  schedule:
    - cron: '00 3 * * *'

jobs:
  check:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: check-style
  crds_contexts:
    uses: spacetelescope/crds/.github/workflows/contexts.yml@master
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      libraries: |
        brew:
          - hdf5
      envs: |
        - linux: py310-xdist
        - linux: py311-xdist
        - macos: py311-xdist
        - linux: py3-cov-xdist
          coverage: codecov