name: PR tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # check:
  #   uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
  #   with:
  #     envs: |
  #       - linux: check-style
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      libraries: |
        brew:
          - hdf5
      envs: |
        - linux: py311
        - macos: py311
        - linux: py312
        - macos: py312
        - linux: py313
        - macos: py313
